services:
  flasky:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    depends_on:
      - dbserver
    restart: always
  
  dbserver:
    image: "mysql:latest"
    env_file: .env_mysql
    restart: always
  