"""登录确认

Revision ID: 2d5dedea61d0
Revises: 3a29aa894c09
Create Date: 2025-04-17 12:02:19.097090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5dedea61d0'
down_revision = '3a29aa894c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_email')
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_index('ix_User_email', ['email'], unique=False)

    # ### end Alembic commands ###
