"""登录确认

Revision ID: 3a29aa894c09
Revises: 27ec707331d0
Create Date: 2025-04-17 09:15:32.716015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a29aa894c09'
down_revision = '27ec707331d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_email')
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_index('ix_User_email', ['email'], unique=1)

    # ### end Alembic commands ###
