"""评论

Revision ID: 499c42234653
Revises: a85ba1fc08f0
Create Date: 2025-04-20 10:04:49.088960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499c42234653'
down_revision = 'a85ba1fc08f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('disbale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disbale', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###
