"""更多用户资料

Revision ID: 87358c9f6b8b
Revises: 6570c0f7615c
Create Date: 2025-04-18 10:05:00.409409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87358c9f6b8b'
down_revision = '6570c0f7615c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
